wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    code_path: code/ppo_impl/ppo_torch/ppo.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1670452595.81608
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.8
      5: 0.13.5
      8:
      - 4
      - 5
gamma:
  desc: null
  value: 0.99
input layer size:
  desc: null
  value: 3
learning rate:
  desc: null
  value: 0.001
output layer size:
  desc: null
  value: 1
timesteps per batch:
  desc: null
  value: 4800
updates per iteration:
  desc: null
  value: 5
